{% set version = "0.8.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-stapler
  version: {{ version|replace("-", "_") }}

source:
  fn: stapler_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/stapler_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stapler/stapler_{{ version }}.tar.gz
  sha256: 0d982bba2842bc76d2179d567b9f85de3d4417a9fa7eec2b8be1a6afe4d1d587

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rnifti
    - r-matrixstats
  run:
    - r-base
    - r-rnifti
    - r-matrixstats

test:
  commands:
    - $R -e "library('stapler')"           # [not win]
    - "\"%R%\" -e \"library('stapler')\""  # [win]

about:
  home: https://github.com/muschellij2/stapler
  license: GPL-3
  summary: An implementation of Simultaneous Truth and  Performance Level Estimation (STAPLE) <doi:10.1109/TMI.2004.828354>.  This method is used when there are multiple raters for an object, typically an image, and this method fuses these ratings into one rating.  It uses an expectation-maximization method to estimate this
    rating and the individual specificity/sensitivity for each rater.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
